### ISSUE TITLE
Script fails after installing VirtualBox Guest Additions

### ISSUE THREAD

**Issue by Tekaoh** [circulosmeos/gdown.pl#17]
Awesome script, by the way. But I'm running into an issue... It works fine on a new installation of Ubuntu in a virtual machine in VirtualBox. But as soon as I install VirtualBox Guest Additions on Ubuntu, I start getting this from the script instead:
`./gdown.pl 'https://drive.google.com/open?id=17wfbfZuL90z4Z_FZPHK7l8FecepZ3dyP' 'LINUX.X64_180000_db_home.zip'`:
![Capture](https://user-images.githubusercontent.com/45337851/65332310-0c4c3e00-db84-11e9-83a4-892bccdab730.PNG)
And I get the same result with v2.0.

I have yet to figure out what difference VirtualBox Guest Additions could be making, or how to continue using the script. Any ideas?

Thanks!

**Comment by Tekaoh** [comment]
Seems I can't even download the file with firefox after installing guest additions. Weird...

**Comment by Tekaoh** [comment]
I've narrowed this down to being a problem with Guest Additions trying to sync the guest time with the host. It's not doing a good job of it, and because the time is wrong, the download fails. I can confirm this by disabling the time sync feature of Guest Additions but leaving the rest of it running, then manually setting the guest clock. The download then works fine. This is not an issue with the script, but rather an issue with Guest Additions screwing up the guest's clock.

**Comment by circulosmeos** [comment]
glad to see you solved your problem :-)
