### ISSUE TITLE
Did not continue to download from the wget-log file.

### ISSUE THREAD

**Issue by TechRancher** [circulosmeos/gdown.pl#18]
I am trying to download a very large 5 gig file. After all day downloading, I went to bed. In the middle of the night, the internet shut down. This morning I started back up to continue the download. But it is starting a new download. I see that the numbers in the wget-log are not the same as what is in the terminal window. Is there a way to just type in the numbers to continue the download from yesterday?

**Comment by circulosmeos** [comment]
Hi,
You have to use [the script on the branch "with-resume" of the project](https://github.com/circulosmeos/gdown.pl/tree/with-resume): Use it just like this to resume:
`$ ./gdown.pl URL my_incomplete`
where **my_incomplete** is whatever name the incomplete file has now. You **must** indicate the name in order for the script to resume the download.

**Comment by TechRancher** [comment]
I did and it did not resume the next day from that wget-log.

**Comment by TechRancher** [comment]
It did the same thing today because I was not able to download the file.
I am see now that each day Google Drive assigned me new numbers. I am
making this assumption because the numbers in the wget-log are different.

**Comment by circulosmeos** [comment]
Can you share the log you're seeing or some parts of it? You can chop part of the link to not reveal it.
