### ISSUE TITLE
Run with php file in cPanel

### ISSUE THREAD

**Issue by burningjibon** [circulosmeos/gdown.pl#20]
In cPanel's file I have cgi-bin folder and I put gdown.pl in that folder.
I've tried to run gdown.pl with below mentioned php file in my root directory:
`<?php
exec('cgi-bin/gdown.pl https://drive.google.com/file/d/0B1L_hFrWJfRhLUJZdXdSdTdfSWs/edit axolotl.mp4');
?>`
But it is showing blank page.
Any Idea?

**Comment by circulosmeos** [comment]
Well, probably the script has executed and has written the file (provided all related permissions are ok), but bear in mind that for php to output anything, you have to control it yourself:   
in particular, [php's exec()](https://www.php.net/manual/en/function.exec.php) has a second parameter that will receive the output so you can [print](https://www.php.net/manual/en/function.print.php) it later.
Also note that php's exec() is synchronous, and so, it'll wait for the command to end before executing the next php sentence. You probably want an asynchronous execution. But all these details are PHP related and require some experience with web programming.
