### ISSUE TITLE
Can't download zip folder.

### ISSUE THREAD

**Issue by ccooddeerr** [circulosmeos/gdown.pl#21]
I plan to download some datasets with zip format,but I find the download link can't apply to your work.
And it's my link :https://doc-0s-28-docs.googleusercontent.com/docs/securesc/1mc8i6ghtriao5nh73ki0clp70uj7hck/al48idlo5m4sqt6jhq9nmooajm8nhmce/1606984050000/15876260727594163214/05147084821579068812/0B3X9GlR6EmbnQ0FtZmJJUXEyRTA?e=download&authuser=0&nonce=cs0n87mgie4no&user=05147084821579068812&hash=clroia7ntuja45qq9bov7cgg1emmfejo

**Comment by circulosmeos** [comment]
The provided link cannot be opened even in the web browser: is it correct?
Also bear in mind that if the content isn't public (require a user) [it cannot be directly downloaded](https://github.com/circulosmeos/gdown.pl/issues/6#issuecomment-425638873).

**Comment by ccooddeerr** [comment]
@circulosmeos This is the location ,and I want to download the second zip https://drive.google.com/drive/folders/1zjtuqMIfgEbKTZ-H-uHqCKS8RPDoYiwc

**Comment by circulosmeos** [comment]
Hi @ccooddeerr 
The link would be (you can see it by selecting "Open in new Window" on the three points menu, after clicking on it):
https://drive.google.com/file/d/11dIpwYIXxi_Cs7afgTnQVj-pIyOmblUe/view

Anyway, in this exact moment it cannot be downloaded (even from a web browser) because it is launching a "**Google Drive - Quota exceeded**": the file that **gdown.pl** downloads now is just this error page:

> Sorry, you can't view or download this file at this time.
> Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by ccooddeerr** [comment]
So can you wait ten hours and try again？

**Comment by ccooddeerr** [comment]
@circulosmeos I want to code a crawler to download, and use scrapy to login.

**Comment by circulosmeos** [comment]
File remains under a **Quota exceeded** error.
