### ISSUE TITLE
gdown.pl does not resume instead re-downloads all over again

### ISSUE THREAD

**Issue by avatar-lavventura** [circulosmeos/gdown.pl#22]
When I try `$ ./gdown.pl https://drive.google.com/file/d/0B1L_hFrWJfRhLUJZdXdSdTdfSWs/edit axolotl.mp4` after it downloaded the file, it starts downloading the same file all over again.

Seems like resume operation does not work on my end, what may be the reason? It keeps generating files as `gdown.2020...` with different name.

**Comment by circulosmeos** [comment]
Hi @avatar-lavventura,
Yes, it seems that something has changed in Google Drive's HTTP behaviour since I last coded [with-resume version](https://github.com/circulosmeos/gdown.pl/tree/with-resume) !

**I've just patched the code**: please, check that everything runs ok now, and that downloads are resumed :-)

**Comment by avatar-lavventura** [comment]
@circulosmeos Thanks for the quick reply it runs ok :-)

**Comment by rrjanbiah** [comment]
FWIW

I was looking for some solutions to download large Google Drive files (RAR files) with resume option and stumbled upon few tools:
1. `youtube-dl` - Tried, but didn't work with RAR files. Error message suggests that it may work with the video files
2. https://github.com/wkentaro/gdown - found some notes that it doesn't support resume and so skipped
3. `gdown.pl` - tried resume branch. First few attempts, it saved only the HTML and then suddenly started to work. So, again searched for other tools.
4. https://github.com/taewookim/wget_gdrive - worked consistently. But, it didn't have resume function and I had to patch/PR with  the `--continue` flag. Perhaps, you may get some idea from here. My 2 cents.

**Comment by circulosmeos** [comment]
Hi @rrjanbiah 
gdown.pl *branch resume* should resume ok :-)
If you see some issue don't hesitate to open an issue to patch it!
Greetings!
