### ISSUE TITLE
ERROR 403: Forbidden

### ISSUE THREAD

**Issue by Jian-danai** [circulosmeos/gdown.pl#23]
![image](https://user-images.githubusercontent.com/42494274/113268596-21be2e80-930a-11eb-91b1-722efe492b26.png)
Hi! Your code is very useful until this happens, it seems I do not have permission to access this google drive file.\
But I can download this file from my Chrome browser directly.

**Comment by circulosmeos** [comment]
Hi @Jian-danai 
Is the file accesible without authentication? 
`gdown.pl` can not access authenticated files.

**Comment by Jian-danai** [comment]
> Hi @Jian-danai
> Is the file accesible without authentication?
> `gdown.pl` can not access authenticated files.

Hi, yes they can be downloaded directly using chrome browser because they are shared with the public. 
And in fact, I could use gdown to download one file of the three at first, but I was forbidden after download one of the files.

A solution is, copy the file to my own google drive, then share it with the public. Then use the new link with gdown to download.

**Comment by circulosmeos** [comment]
May be Google limited access to the file [due to high traffic (quota exceeded)](https://github.com/circulosmeos/gdown.pl/issues/21#issuecomment-737881365)?

**Comment by Jian-danai** [comment]
> May be Google limited access to the file [due to high traffic (quota exceeded)](https://github.com/circulosmeos/gdown.pl/issues/21#issuecomment-737881365)?

Yes, it's possible. But it can be downloaded using my Windows Chrome. That's weird. Anyway, copying it to my own drive is a stupid but satisfactory solution.
