### ISSUE TITLE
how to resume download

### ISSUE THREAD

**Issue by iris0329** [circulosmeos/gdown.pl#7]
I have a 256G dataset need to be download from google drive, the connection will break, so can this tool resume download?
thanks for help!!!

**Comment by iris0329** [comment]
thanks a lot!!!

**Comment by circulosmeos** [comment]
Unfortunately, v1.2 doesn't run correctly: please, [test v2.0](https://github.com/circulosmeos/gdown.pl/tree/with-resume) instead.

**Comment by circulosmeos** [comment]
Unfortunately, v1.2 doesn't run correctly: please, [test v2.0](https://github.com/circulosmeos/gdown.pl/tree/with-resume) instead.

**Comment by circulosmeos** [comment]
[v2.0 with resuming capabilities](https://github.com/circulosmeos/gdown.pl/tree/with-resume) will be left in a different branch for now.
